const INCORRECT_INPUT_ERROR = 400;
const UNAUTHORIZED_ERROR = 401;
const NOT_FOUND_ERROR = 404;
const DEFAULT_ERROR = 500;

module.exports = {
  INCORRECT_INPUT_ERROR,
  NOT_FOUND_ERROR,
  DEFAULT_ERROR,
  UNAUTHORIZED_ERROR,
};
